### ISSUE TITLE
Question: Is DevDokus required to use the Metabolism portion?

### ISSUE THREAD

**Issue by TheDevster** [DevDokus/RedM-Metabolism#1]
Thanks for the answer!

**Comment by DevDokus** [comment]
My Metabolism script works together with DevDokus--UsableItems
https://github.com/DevDokus/RedM-UsableItems

But if you want to have the packages all in one without needing
to worry about the resources DokusCore would be a better pick.
https://github.com/DevDokus/DokusCore
